<?php
/**
 * @file
 * code_qa module implementation
 */

module_load_include('inc', 'code_qa', 'code_qa.admin');
module_load_include('inc', 'code_qa', 'code_qa.phploc');

/**
 * Implements hook_menu().
 */
function code_qa_menu() {
  $items = array();

  $items['admin/code_qa'] = array(
    'title' => 'Code QA',
    'access callback' => TRUE,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('code_qa_admin_page'),
    'type' => MENU_CALLBACK,
  );

  $items['admin/code_qa/phploc'] = array(
    'title' => 'Code QA: PHPLOC',
    'access callback' => TRUE,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('code_qa_phploc_report_page'),
    'type' => MENU_CALLBACK,
  );

  $items['admin/code_qa/phploc/%'] = array(
    'title' => 'Code QA: PHPLOC Details',
    'access callback' => TRUE,
    'page arguments' => array(1),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('code_qa_phploc_report_module_page', 3),
    'type' => MENU_CALLBACK,
  );

  return $items;
}


function code_qa_get_projects($header = NULL) {
  $query = db_select('code_qa_project', 'p')
    ->fields('p',
      array(
        'pid',
        'name',
        'url',
      )
    )
    ->extend('TableSort');

  if($header) {
    $query->orderByHeader($header);
  }
  $result = $query->execute();

  return $result;
}


function code_qa_get_filepath() {
  // TODO

  $path = '/tmp/code_qa';

  return $path;
}
