<?php

/**
 * @file
 * Project QA Git Commit entity code.
 */

/**
 * Implements hook_entity_info().
 */
function project_qa_gitcommit_entity_info() {
  return array(
    'project_qa_gitcommit' => array(
      'label' => t('Project QA Git Commit'),
      'entity class' => 'CodeQAGitCommit',
      'controller class' => 'CodeQAGitCommitController',
      'base table' => 'project_qa_gitcommit',
      'uri callback' => 'project_qa_gitcommit_uri',
      'fieldable' => TRUE,
      'entity keys' => array(
        'id' => 'gcid',
      ),
      'static cache' => TRUE,
      'module' => 'project_qa_gitcommit',
      'views controller class' => 'EntityDefaultViewsController',
    ),
  );
}


/**
 * Implements hook_entity_property_info().
 */
function project_qa_gitcommit_entity_property_info() {
  $info = array();
  $properties = &$info['project_qa_gitcommit']['properties'];

  $properties['gcid'] = array(
    'label' => 'Git commit ID',
    'description' => t('The unique ID for the git commit.'),
    'type' => 'integer',
    'schema field' => 'gcid',
  );
  $properties['sha1'] = array(
    'label' => 'SHA1',
    'description' => t('The sha1 of the git commit'),
    'type' => 'integer',
    'schema field' => 'sha1',
  );
  $properties['pid'] = array(
    'label' => 'Project ID',
    'description' => t('The project repo id.'),
    'type' => 'project_qa_repo',
    'schema field' => 'pid',
  );
  $properties['timestamp'] = array(
    'label' => 'Timestamp',
    'description' => t('The Unix timestamp for the git commit.'),
    'type' => 'date',
    'schema field' => 'timestamp',
  );
  $properties['author'] = array(
    'label' => 'Author',
    'description' => t('The author of the git commit.'),
    'type' => 'text',
    'schema field' => 'author',
  );

  return $info;
}


/**
 * Access callback.
 */
function project_qa_gitcommit_access($op, $project_qa_gitcommit, $account = NULL, $entity_type = NULL) {
  global $user;
  if (!isset($account)) {
    $account = $user;
  }
  switch ($op) {
    case 'create':
      return user_access('administer project_qa_gitcommit entities', $account)
          || user_access('create project_qa_gitcommit entities', $account);
    case 'view':
      return user_access('administer project_qa_gitcommit entities', $account)
          || user_access('view project_qa_gitcommit entities', $account);
    case 'edit':
      return user_access('administer project_qa_gitcommit entities')
          || user_access('edit any project_qa_gitcommit entities')
          || (user_access('edit own project_qa_gitcommit entities') && ($task->uid == $account->uid));
  }
}


/**
 * Implements hook_permission().
 */
function project_qa_gitcommit_permission() {
  $permissions = array(
    'create project_qa_gitcommit entities' => array(
      'title' => t('Create project_qa_gitcommit'),
      'description' => t('Allows users to create project_qa_gitcommit.'),
      'restrict access' => TRUE,
    ),
    'view project_qa_gitcommit entities' => array(
      'title' => t('View project_qa_gitcommit'),
      'description' => t('Allows users to view project_qa_gitcommit.'),
      'restrict access' => TRUE,
    ),
    'edit any project_qa_gitcommit entities' => array(
      'title' => t('Edit any project_qa_gitcommit'),
      'description' => t('Allows users to edit any project_qa_gitcommit.'),
      'restrict access' => TRUE,
    ),
    'edit own project_qa_gitcommit entities' => array(
      'title' => t('Edit own project_qa_gitcommit'),
      'description' => t('Allows users to edit own project_qa_gitcommit.'),
      'restrict access' => TRUE,
    ),
  );
  return $permissions;
}


/**
 * CodeQAGitCommit class.
 */
class CodeQAGitCommit extends Entity {

  /**
   * The default label.
   *
   * @return int
   *   project_qa_gitcommit id
   */
  protected function defaultLabel() {
    return $this->gcid;
  }

  /**
   * The default URI.
   *
   * @return array
   *   An array containing the path to the project_qa_gitcommit
   */
  protected function defaultUri() {
    return array('path' => 'project_qa_gitcommit/' . $this->identifier());
  }
}


/**
 * CodeQAProjectController class
 */
class CodeQAGitCommitController extends EntityAPIController {

  /**
   * Create a project_qa_gitcommit.
   *
   * @param array $values
   *   The values of the project_qa_gitcommit object to create.
   *
   * @return
   */
  public function create(array $values = array()) {
    return parent::create($values);
  }

  /**
   * Implementing buildContent().
   */
  public function buildContent($entity, $view_mode = 'full', $langcode = NULL, $content = array()) {
    $wrapper = entity_metadata_wrapper('project_qa_gitcommit', $entity);
    return parent::buildContent($entity, $view_mode, $langcode, $content);
  }
}


/**
 * Load.
 */
function project_qa_gitcommit_load($gcid, $reset = FALSE) {
  $project_qa_gitcommits = project_qa_gitcommit_load_multiple(array($gcid), array(), $reset);
  return reset($project_qa_gitcommits);
}


/**
 * Load multiple based on certain conditions.
 */
function project_qa_gitcommit_load_multiple($gcid = array(), $conditions = array(), $reset = FALSE) {
  return entity_load('project_qa_gitcommit', $gcid, $conditions, $reset);
}


/**
 * Save.
 */
function project_qa_gitcommit_save($project_qa_gitcommit) {
  entity_save('project_qa_gitcommit', $project_qa_gitcommit);
}


/**
 * Delete single.
 */
function project_qa_gitcommit_delete($project_qa_gitcommit) {
  entity_delete('project_qa_gitcommit', entity_id('project_qa_gitcommit', $project_qa_gitcommit));
}


/**
 * Delete multiple.
 */
function project_qa_gitcommit_delete_multiple($project_qa_gitcommit_ids) {
  entity_delete_multiple('project_qa_gitcommit', $project_qa_gitcommit_ids);
}
