<?php

/**
 * @file
 * Project QA Project entity code.
 */

/**
 * Implements hook_entity_info().
 */
function project_qa_repo_entity_info() {
  return array(
    'project_qa_repo' => array(
      'label' => t('Project QA Project'),
      'entity class' => 'ProjectQARepo',
      'controller class' => 'ProjectQARepoController',
      'base table' => 'project_qa_repo',
      'uri callback' => 'project_qa_repo_uri',
      'fieldable' => TRUE,
      'entity keys' => array(
        'id' => 'pid',
      ),
      'static cache' => TRUE,
      'module' => 'project_qa_repo',
      'views controller class' => 'EntityDefaultViewsController',
    ),
  );
}


/**
 * Access callback.
 */
function project_qa_repo_access($op, $project_qa_repo, $account = NULL, $entity_type = NULL) {
  global $user;
  if (!isset($account)) {
    $account = $user;
  }
  switch ($op) {
    case 'create':
      return user_access('administer project_qa_repo entities', $account)
          || user_access('create project_qa_repo entities', $account);
    case 'view':
      return user_access('administer project_qa_repo entities', $account)
          || user_access('view project_qa_repo entities', $account);
  }
}


/**
 * Implements hook_permission().
 */
function project_qa_repo_permission() {
  $permissions = array(
    'create project_qa_repo entities' => array(
      'title' => t('Create project_qa_repo'),
      'description' => t('Allows users to create project_qa_repo.'),
      'restrict access' => TRUE,
    ),
    'view project_qa_repo entities' => array(
      'title' => t('View project_qa_repo'),
      'description' => t('Allows users to view project_qa_repo.'),
      'restrict access' => TRUE,
    ),
  );
  return $permissions;
}


/**
 * ProjectQARepo class.
 */
class ProjectQARepo extends Entity {

  /**
   * The default label.
   *
   * @return int
   *   project_qa_repo id
   */
  protected function defaultLabel() {
    return $this->prid;
  }

  /**
   * The default URI.
   *
   * @return array
   *   An array containing the path to the project_qa_repo
   */
  protected function defaultUri() {
    return array('path' => 'project_qa_repo/' . $this->identifier());
  }
}


/**
 * ProjectQARepoController class
 */
class ProjectQARepoController extends EntityAPIController {}
